package com.task;

public class Test {

	/*
	 * private void m1() { m2();//goes to m2 System.out.println("1");//1 will be
	 * printed in console after the 2 } private void m2() { m3();//goes to m3
	 * System.out.println("2");//2 will be printed in console after the 7 } private
	 * void m3() { System.out.println("3");//prints 3 in console try { int sum =
	 * 4/0;//Arithmetic Exception, so it goes to catch System.out.println("4"); }
	 * catch(ArithmeticException e) { System.out.println("5");// 5 will be printed
	 * in console }
	 * 
	 * System.out.println("7");//7 will be printed in console } public static void
	 * main(String[] args) { Test obj = new Test(); obj.m1();//At first, program
	 * will read main }
	 */
	 
	/*
	 * public static void main(String[] args) { try { System.out.println("1");//
	 * print 1 in console window int data = 5 / 0;//Arithmetic exception }
	 * catch(ArithmeticException e) { System.out.println("2");// 2 will be printed
	 * in console screen System.exit(0);//.exit is used, so the program will
	 * terminate,the finally block won't execute } finally {
	 * System.out.println("3"); } System.out.println("4"); }
	 */
		 }
	


